trigger:
    branches:
        include:
            - master
    paths:
        include:
            - ui
            - api
pool:
    name: 'Default'

jobs:

- job: project_ui_job
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install dependancies'

  - script: |
      cd ui
      npm ci
    displayName: 'NPM CI'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Run project build'

  - script: |
      cd ui
      dir
      npm run build
    displayName: 'NPM RUN BUILD'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'List files and folders in the current directory'

  - script: |
      cd ui
      dir
    displayName: 'DIR command output'

  - task: ArchiveFiles@2
    displayName: 'Archive UI build files'  
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/ui/dist'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactDirectory)/$(Build.BuildId).zip'
      archiveType: 'zip'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish UI artifact'
    inputs:
      targetPath: '$(Build.ArtifactDirectory)/$(Build.BuildId).zip'
      artifact: 'ui_artifact'
      
  - script: |
      cd ui/dist

- job: project_api_job
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install API dependencies'

    - script: |
        cd api
        npm ci
      displayName: 'NPM CI for API'

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Run API build'

    - script: |
        cd api
        npm run build
      displayName: 'NPM RUN BUILD for API'

    - task: ArchiveFiles@2
      displayName: 'Archive API build files'  
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/api/dist'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactDirectory)/$(Build.BuildId)_api.zip'
        archiveType: 'zip'
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish API artifact'
      inputs:
        targetPath: '$(Build.ArtifactDirectory)/$(Build.BuildId)_api.zip'
        artifact: 'api_artifact'