trigger:
    branches:
        include:
            - master
    paths:
        include:
            - .
pool:
    name: 'Default'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script:
        npm ci
        npm run build
    displayName: 'Install dependancies and build'
    
  - script: dir
    displayName: 'List files and folders in the current directory'

  - task: PublishBuildArtifacts@1
    inputs:
     PathtoPublish: 'dist'
     ArtifactName: 'drop'
     publishLocation: 'Container'