trigger:
    branches:
        include:
            - master

    paths:
        include:
            - ui
            - api

pool:
    name: 'Default'

jobs:

- job: first_project_ui_job
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install dependancies'

  - script: |
      cd ui
      npm ci
    displayName: 'NPM CI'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Run project build'

  - script: |
      cd ui
      npm run build
    displayName: 'NPM RUN BUILD for first ui project'

  - task: ArchiveFiles@2
    displayName: 'Archive UI build files'  
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/ui/dist'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactDirectory)/$(Build.BuildId).zip'
      archiveType: 'zip'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish UI artifact'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      targetPath: '$(Build.ArtifactDirectory)/$(Build.BuildId).zip'
      artifact: 'ui_artifact'

- job: second_project_ui_job
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install API dependencies'

    - script: |
        cd api
        npm ci
      displayName: 'NPM CI for API'

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Run project build'

    - script: |
        cd api
        npm run build
      displayName: 'NPM RUN BUILD for second ui project'

    - task: ArchiveFiles@2
      displayName: 'Archive API build files'  
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/api/dist'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactDirectory)/$(Build.BuildId)_api.zip'
        archiveType: 'zip'
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish API artifact'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      inputs:
        targetPath: '$(Build.ArtifactDirectory)/$(Build.BuildId)_api.zip'
        artifact: 'api_artifact'